name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - spark: "2.4.1"
            scala-major: "2.11"
            scala-minor: "2.11.12"
            hadoop: "2.7"
            python: "3.7"
          - spark: "2.4.7"
            scala-major: "2.11"
            scala-minor: "2.11.12"
            hadoop: "2.7"
            python: "3.7"
          - spark: "2.4.8"
            scala-major: "2.11"
            scala-minor: "2.11.12"
            hadoop: "2.7"
            python: "3.7"
          - spark: "3.0.0"
            scala-major: "2.12"
            scala-minor: "2.12.12"
            hadoop: "2.7"
            python: "3.8"
          - spark: "3.0.3"
            scala-major: "2.12"
            scala-minor: "2.12.12"
            hadoop: "2.7"
            python: "3.8"
          - spark: "3.1.1"
            scala-major: "2.12"
            scala-minor: "2.12.12"
            hadoop: "2.7"
            python: "3.8"
          - spark: "3.1.2"
            scala-major: "2.12"
            scala-minor: "2.12.12"
            hadoop: "2.7"
            python: "3.8"
          - spark: "3.2.1"
            scala-major: "2.12"
            scala-minor: "2.12.12"
            hadoop: "2.7"
            python: "3.8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Cache SBT
        uses: actions/cache@v2
        with:
            path: |
                ~/.ivy2/cache
                ~/.sbt
            key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Test
        run: sbt -Dspark.testVersion=${{ matrix.spark  }} ++${{ matrix.scala-minor }} test
      - name: Assembly
        run: sbt ++${{ matrix.scala-minor }} assembly
      - name: Scalastyle
        run: sbt ++${{ matrix.scala-minor }} scalastyle "test:scalastyle"
      - name: Download Spark
        run: |
          curl -s https://archive.apache.org/dist/spark/spark-${{ matrix.spark }}/spark-${{ matrix.spark }}-bin-hadoop${{ matrix.hadoop }}.tgz | tar xvz
      - name: Run Spark Test
        run: |
          "${SPARK_HOME}/bin/spark-submit" --jars "$( ls -m target/scala-${{ matrix.scala-major }}/*.jar )" src/test/python/integration-test.py "src/test/resources/spreadsheets/apache_poi/57231_MixedGasReport.xls"
        env:
          SPARK_HOME: ./spark-${{ matrix.spark }}-bin-hadoop${{ matrix.hadoop }}